[server]
name = "scoreboard"

[api]
ip = false
port = 6969

[configs]
board_layout = "config/board_layout.toml"
characters = "config/characters.toml"


[plugins]
dir = "src.plugins"

[plugins.p.time]
active = true
auto_start = true
config_file = "time/config.toml"