[server]
name = "scoreboard"

[api]
ip = false
port = 6969
base_url = "/rest"

[configs]
board_layout = "config/board_layout.toml"
characters = "config/characters.toml"


[plugins]
dir = "src.plugins"

[plugins.p.time]
active = true
autostart = true

[plugins.p.time.init]
self_resource = true

[plugins.p.time.init.args]
config_file = "config.toml"

[plugins.p.time.init.resources]
board = "board"