# the layout
#
# A G G B
# J     K
# J     K
# C H H B
# L     M
# L     M
# E I I B



[other]
all = [
    "A",
    "G",
    "B",
    "J",
    "K",
    "C",
    "H",
    "L",
    "M",
    "E",
]


[numbers]
0 = [
    "A",
    "G",
    "B",
    "J",
    "K",
    "C",
    "L",
    "M",
    "E",
]

1 = [
    "B",
    "K",
    "M",
]

2 = [
    "A",
    "G",
    "B",
    "K",
    "C",
    "H",
    "L",
    "E",
]

3 = [
    "A",
    "G",
    "B",
    "K",
    "C",
    "H",
    "M",
    "E",
]

4 = [
    "A",
    "B",
    "J",
    "K",
    "C",
    "H",
    "M",
]

5 = [
    "A",
    "G",
    "B",
    "J",
    "C",
    "H",
    "M",
    "E",
]

6 = [
    "A",
    "G",
    "B",
    "J",
    "C",
    "H",
    "L",
    "M",
    "E",
]

7 = [
    "A",
    "G",
    "B",
    "K",
    "M",
]

8 = [
    "A",
    "G",
    "B",
    "J",
    "K",
    "C",
    "H",
    "L",
    "M",
    "E",
]

9 = [
    "A",
    "G",
    "B",
    "J",
    "K",
    "C",
    "H",
    "M",
    "E",
]